sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t hozefam/docker-angular-app -f Dockerfile.dev .

script:
  - docker run -e CI=true hozefam/docker-angular-app npm run test
